name: dictionary_game
description: A Dictionary Game
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.13.3
  random_words: ^1.0.2
  english_words: ^4.0.0
  font_awesome_flutter: ^9.0.0
  audioplayers: ^0.20.1
  cupertino_icons: ^1.0.2
  flutter_spinkit: ^5.1.0
  rflutter_alert: ^2.0.4
  shared_preferences: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/

  fonts:
    - family: Bloxat
      fonts:
        - asset: fonts/Bloxat.ttf

